name: PAKSA TOTAL BUILD
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v4

      - name: Siapin Lingkungan
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3-setuptools libffi-dev libssl-dev libltdl-dev zip unzip openjdk-17-jdk
          pip3 install --user --upgrade buildozer cython==0.29.33

      - name: Bersihkan & Rakit
        run: |
          export PATH=$PATH:~/.local/bin
          # Hapus sisa-sisa build gagal
          buildozer android clean
          # Rakit paksa
          yes | buildozer -v android debug
